name: Cache Workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/test-cache
          key: cache-64ec23b

      - name: prime-cache-64ec23b
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
